[font]

normal.family = "CommitMono Nerd Font"
bold.family = "CommitMono Nerd Font"
italic.family = "CommitMono Nerd Font"
bold_italic.family = "CommitMono Nerd Font"
offset.y = 2

[window]

decorations = "None"
opacity = 0.8

[window.padding]

x = 0
y = 0

